#  Numpy 


## 1 Creating array

### 1.1  Creating 0-D array

In [ ]:
import numpy as np

arr = np.array(42)

print(arr)
print(type(arr))


42
<class 'numpy.ndarray'>


### 1.2  Creating 1-D array

In [ ]:
#import numpy as np

arr = np.array([1, 2, 3, 4, 5])
#arr1=[1, 2, 3, 4, 5]
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


### 1.3  Creating 2-D array

In [ ]:
#import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)


[[1 2 3]
 [4 5 6]]


### 1.4  Creating 3-D array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### 1.5  Check the of Dimension of Array

In [ ]:
#import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


### 1.6 Access Array Elements

In [ ]:
#import numpy as np

arr = np.array([1, 2.5, 3, 4])

print(type(arr[0]))
print(type(arr[1]))
print(arr[2] + arr[3])   #adding 2nd and 3rd elements


<class 'numpy.float64'>
<class 'numpy.float64'>
7.0


### 1.7 Access 2-D array 

In [ ]:
#import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print('2nd element on 1st dim: ', arr[0, 1])
print('5th element on 2nd dim: ', arr[1, 4])
print( arr[0, 4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
2nd element on 1st dim:  2
5th element on 2nd dim:  10
5


### 1.8 Access 3-D array

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 1])


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
5


In [ ]:
d=([[[1, [4,5,6],2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(len(d[0][0][1]))
#print(a[])

3


### 1.9 Negative Indexing

In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)

print('Last element from 2nd dim: ', arr[1, -1])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Last element from 2nd dim:  10


## 2 Array Slicing

### 2.1 Slicing 1-D Array 

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]


### 2.2 Slicing 2-D

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr)
#print(arr[1, 1:4])
print(arr[0:, 2:]) #return index 2
#print(arr[:, 1:4]) # slice index 1 to index 4 (not included)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 3  4  5]
 [ 8  9 10]]


# 3 Data Types in Python
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )


### 3.1 Checking Data type of array

In [ ]:
#import numpy as np

arr = np.array([1, 2, 3, 4])
print(type(arr))
print(arr.dtype)

arr1 = np.array(['apple', 'banana', 'cherry'])

print(arr1.dtype)


<class 'numpy.ndarray'>
int64
<U6


### 3.2 Creating Arrays with a defined Data Type

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')
 
print(arr)
print(arr.dtype)
arr1 = np.array(['a', '2', '3'], dtype='i') #Error


[b'1' b'2' b'3' b'4']
|S1


ValueError: ignored

In [ ]:
# Example 2:

import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')   # arr.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int32


In [ ]:
# Example 3:

import numpy as np

arr = np.array([1, 0,0,2, 3])

newarr = arr.astype(bool) # converting in Boolean

print(newarr)
print(newarr.dtype)


[ True False False  True  True]
bool


### 3.3 Copy and View

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)
# The copy owns the data and any changes made to the copy will 
# not affect original array, and any #changes made to the 
# original array will not affect the copy.


[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
x[1]=4

print(arr)
print(x)
#The view does not own the data and any changes made 
#to the view will affect the original array, and any 
#changes made to the original array will affect the view.


[42  4  3  4  5]
[42  4  3  4  5]


### 3.4 Get the shape of array

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)

print(arr.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


### 3.5 Array Reshaping

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3, 4)  #1D to 2D

print(newarr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(3,2 ,2)  #1D to 3D

print(newarr)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# Example 3:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)  # Error

print(newarr)


ValueError: ignored

### 3.6 Iterating Arrays

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3,3,4,5,3,2,2,3,4]) #1D

for x in arr:
      print(x)

1
2
3
3
4
5
3
2
2
3
4


In [ ]:
# Example 2:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])  #2D

for x in arr:
    print(x)


In [ ]:
# Example 3:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
for x in arr:
    for y in x:
        print(y)

[[1 2 3]
 [4 5 6]]
1
2
3
4
5
6


In [ ]:
# Example 4:
    
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])   #3D

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### 3.7 Use of nditer()

In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)


1
2
3
4
5
6
7
8


### 3.8 Using ndenumerate()

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)


(0,) 1
(1,) 2
(2,) 3


In [ ]:
# Example 2:

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print()

for idx, x in np.ndenumerate(arr):
    print(idx, x)


[[1 2 3 4]
 [5 6 7 8]]

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


### 3.9 Joining array

In [ ]:
# Example 1:

#import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

print(arr1)

arr2 = np.array([[5, 6], [7, 8]])

print(arr2)

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)


[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


### 3.10 Splitting array

In [ ]:
# Example 1: 

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3) # split into arrays

print(newarr[0])
print(newarr[1])
print(newarr[2])


[1 2]
[3 4]
[5 6]


### 3.11 Searching

In [ ]:
# Example 1:

#import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6]),)


In [ ]:
# Example 2: Finding where the values are even

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7]),)


### 3.12 Binary Search

In [ ]:
# Example 1:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)


1


In [ ]:
# Example 2:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [3,7]) #searching multiple values

print(x)


[1 3]


### 3.13 Sorting array

In [ ]:
# Example 1:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))


[0 1 2 3]


In [ ]:
# Example 2:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))


['apple' 'banana' 'cherry']


In [ ]:
# Example 3:

import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))


[[2 3 4]
 [0 1 5]]


### 3.14 Filter array

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, True]

newarr = arr[x]

print(newarr)

[41 43 44]


### 3.15 Random Numbers

In [ ]:
#Example 1: 

from numpy import random

x = random.randint(100)  #integer

print(x)

x1 = random.rand()     #Float
print(x1)


48
0.4070871219196589


In [ ]:
# Example 2: Random array

from numpy import random

x=random.randint(100, size=(5))

print(x)

x1 = random.rand(5)

print(x1)


[ 9 63 19  3 79]
[0.41436492 0.23932602 0.76234924 0.21316494 0.2968727 ]


In [ ]:
# Example 3:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

x1 = random.rand(3, 5)
print(x1)


[[37 12  3 32 83]
 [87  8 42 38 89]
 [91 89 50 80 50]]
[[0.67224786 0.62259472 0.61300017 0.40144235 0.91434956]
 [0.06417904 0.52109899 0.79281842 0.6170785  0.07976986]
 [0.91733384 0.89005976 0.06575571 0.73306599 0.24550184]]


In [ ]:
# Example 4: Generate a random value based on an array of values.

from numpy import random

x = random.choice([3, 5, 7, 9])# size=(3, 5)

print(x)


9


### 3.16 Shuffle and Permutation

In [ ]:
# Example 1:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

random.shuffle(arr)

print(arr)


[1 4 3 2 5]


In [ ]:
# Example 2:

from numpy import random
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(random.permutation(arr))
print(arr)#original array is unchanged


[1 4 2 3 5]
[1 2 3 4 5]


### 3.17 Arithmetic Operations

In [ ]:
# Example 1:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Add = Matrix_1 + Matrix_2

print(Add)


[[12 16 20]
 [14 18 22]
 [24 26 28]]


In [ ]:
# Example 2:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Subtract = Matrix_1 - Matrix_2

print(Subtract)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [ ]:
# Example 3:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

Multiply = Matrix_1 * Matrix_2

print(Multiply)


[[ 11  39  75]
 [ 24  56  96]
 [119 144 171]]


In [ ]:
# Example 4:

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print("Original Matrix",Matrix_1)

Matrix_1.T
#Transpose of the Matrix_1.

Original Matrix [[1 3 5]
 [2 4 6]
 [7 8 9]]


array([[1, 2, 7],
       [3, 4, 8],
       [5, 6, 9]])

In [ ]:
# Example 5:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print(Matrix_2)

print("Diagonal Values are: ", Matrix_2.diagonal())
#Accessing the diagonal of the Matrix_2.


[[11 13 15]
 [12 14 16]
 [17 18 19]]
Diagonal Values are:  [11 14 19]


In [ ]:
# Example 6:
    
Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print(Matrix_1)
print("Sum of diagonal elements is:", Matrix_1.trace())
#Returns the sum of diagonal elements of the Matrix_1.

[[1 3 5]
 [2 4 6]
 [7 8 9]]
Sum of diagonal elements is: 14


In [ ]:
# Example 7:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])

print(Matrix_2)
print("Maximum value is:", np.max(Matrix_2))
#Returns the maximum element of the matrix Matrix_2.


Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])

print(Matrix_1)
print("Minimum value is:",np.min(Matrix_1))
#Returns the minimum element of the Matrix_1.

[[11 13 15]
 [12 14 16]
 [17 18 19]]
Maximum value is: 19
[[1 3 5]
 [2 4 6]
 [7 8 9]]
Minimum value is: 1


In [ ]:
# Example 8:

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print("Mean is:",np.mean(Matrix_2))
#It calculates the mean of the matrix.

Matrix_2 = np.array([[11,13,15],[12,14,16],[17,18,19]])
print("Variance is:",np.var(Matrix_2))
#It calculates the variance of the matrix.

Matrix_1 = np.array([[1,3,5],[2,4,6],[7,8,9]])
print("Standard Deviation is:",np.std(Matrix_1))
#It calculates the standard deviation of the matrix.

Mean is: 15.0
Variance is: 6.666666666666667
Standard Deviation is: 2.581988897471611


## 4 Arithmetic Operations by using functions

In [ ]:

arr15 = np.array([[5,10],[15,20]])
arr16 = np.array([[6,12],[18,24]])
#Let us define 2 arrays.

print(arr15)
print(arr16)
print("Addition:",np.add(arr15,arr16))

print("Subtraction:",np.subtract(arr15,arr16))
#Subtraction of 2 arrays.

print("Division:",np.divide(arr15,arr16))
#Division of 2 arrays.

print("Multiplication:",np.multiply(arr15,arr16))
#Multiplication of 2 arrays.

print("Square Root:",np.sqrt(arr15))
#Returns the square root of the values in the array.


[[ 5 10]
 [15 20]]
[[ 6 12]
 [18 24]]
Addition: [[11 22]
 [33 44]]
Subtraction: [[-1 -2]
 [-3 -4]]
Division: [[0.83333333 0.83333333]
 [0.83333333 0.83333333]]
Multiplication: [[ 30 120]
 [270 480]]
Square Root: [[2.23606798 3.16227766]
 [3.87298335 4.47213595]]


### 4.1 Remainder

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)    

print(newarr)


[ 1  6  3  0  0 27]


### 4.2 Power

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])

newarr = np.power(arr1, arr2)    

print(newarr)


[         1000       3200000     729000000 6553600000000          2500
             0]


### 4.3 Absolute Value

In [ ]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)   #Absolute Values

print(newarr)


[1 2 1 2 3 4]


### 4.4 Trignometry Functions

In [ ]:
import numpy as np

arr16 = np.array([[6,12],[18,24]])
print(np.sin(arr16))
#Returns the trigonometric values of 'sin' applied on array 'arr16'.


arr15 = np.array([[5,10],[15,20]])
print(np.cos(arr15))

print(np.log(arr16))
#Returns the log value of the array 'arr16'.


[[-0.2794155  -0.53657292]
 [-0.75098725 -0.90557836]]
[[ 0.28366219 -0.83907153]
 [-0.75968791  0.40808206]]
[[1.79175947 2.48490665]
 [2.89037176 3.17805383]]


### 4.5 Mean, Median, SD and Correlation

In [ ]:
arr15 = np.array([[5,10],[15,20]])

print(np.mean(arr15))
#This returns mean of the array.

arr16 = np.array([[6,12],[18,24]])
print(np.median(arr16))
#This returns the median of the array.


print(np.std(arr15))
#Returns the standard deviation of the array.

#print(np.corr(arr15))
#Returns the correlation coefficient between the arrays.


12.5
15.0
5.5901699437494745


AttributeError: ignored

### 4.6 Rounding Decimals

In [ ]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)


arr1 = np.fix([-3.1666, 3.6667]) #same as trunc()

print(arr1)


arr2 = np.around(3.1666, 2)

print(arr2)

arr3 = np.floor([-3.1666, 3.6667])

print(arr3)

arr4 = np.ceil([-3.1666, 3.6667])

print(arr4)


[-3.  3.]
[-3.  3.]
3.17
[-4.  3.]
[-3.  4.]


### 4.7 Log

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

print(np.log10(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


### 4.8 Summation and Addition

In [ ]:
# Example 1:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)


[2 4 6]


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

newarr1 = np.sum([arr1, arr2], axis=1) #axis=0 means columns sum, 1 means rows sum
print(newarr1)

12
[6 6]


### 4.9 Product

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)


24


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])  #newarr = np.prod([arr1, arr2], axis=1)

print(x)


40320


### 4.10 Sets operation

In [ ]:
# Example 1:

import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

print(x)


[1 2 3 4 5 6 7]


In [ ]:
# Example 2:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)  # find Union

print(newarr)


[1 2 3 4 5 6]


In [ ]:
# Example 3:

import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)  #intersection

print(newarr)


[3 4]


In [ ]:
# Example 4: difference

import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)


[1 2]
